export type AccountStatus = "healthy" | "watch" | "at_risk" | "critical";

export type SeedAccount = {
  slug: string;
  name: string;
  industry: string;
  arr: number;
  plan: "starter" | "growth" | "enterprise";
  renewalDays: number;
  status: AccountStatus;
  csm: string;
  champion: { name: string; title: string; status: "active" | "silent" | "departed" };
  signalCount: number;
  lastActivity: string;
  oneLineWhy: string;
  isLive: boolean;
};

export const ACCOUNTS: SeedAccount[] = [
  {
    slug: "accounts/acme-corp",
    name: "Acme Corp",
    industry: "DevOps Observability",
    arr: 240_000,
    plan: "enterprise",
    renewalDays: 47,
    status: "critical",
    csm: "Sarah Kim",
    champion: { name: "Jordan Chen", title: "Director of Engineering", status: "silent" },
    signalCount: 4,
    lastActivity: "14 days silent",
    oneLineWhy: "Champion went silent post-promotion; technical user frustrated; renewal close",
    isLive: true,
  },
  {
    slug: "accounts/lattice-grid",
    name: "Lattice Grid",
    industry: "B2B Fintech",
    arr: 410_000,
    plan: "enterprise",
    renewalDays: 89,
    status: "at_risk",
    csm: "Sarah Kim",
    champion: { name: "Priya Sundaram", title: "VP Engineering", status: "active" },
    signalCount: 2,
    lastActivity: "2 days ago",
    oneLineWhy: "Two product feedback escalations open >14 days, NPS dropped from 9 to 6",
    isLive: false,
  },
  {
    slug: "accounts/northwind-labs",
    name: "Northwind Labs",
    industry: "ML Infra",
    arr: 180_000,
    plan: "growth",
    renewalDays: 121,
    status: "watch",
    csm: "Sarah Kim",
    champion: { name: "Diego Alvarez", title: "Staff Engineer", status: "active" },
    signalCount: 1,
    lastActivity: "5 hrs ago",
    oneLineWhy: "Usage flat for 21 days; expansion conversation paused after kickoff",
    isLive: false,
  },
  {
    slug: "accounts/halcyon-ai",
    name: "Halcyon AI",
    industry: "Vertical AI / Legal",
    arr: 96_000,
    plan: "growth",
    renewalDays: 14,
    status: "critical",
    csm: "Sarah Kim",
    champion: { name: "Maya Roth", title: "Head of Engineering", status: "departed" },
    signalCount: 5,
    lastActivity: "1 day ago",
    oneLineWhy: "Champion left for OpenAI 9d ago; no replacement; renewal in 2 weeks",
    isLive: false,
  },
  {
    slug: "accounts/sundial-os",
    name: "Sundial OS",
    industry: "Workflow / SMB",
    arr: 60_000,
    plan: "growth",
    renewalDays: 67,
    status: "healthy",
    csm: "Sarah Kim",
    champion: { name: "Tomás Vega", title: "CTO", status: "active" },
    signalCount: 0,
    lastActivity: "today",
    oneLineWhy: "Expansion signal: requested SSO + audit log, both unlock the enterprise tier",
    isLive: false,
  },
  {
    slug: "accounts/anchorpoint-io",
    name: "Anchorpoint.io",
    industry: "Gamedev SaaS",
    arr: 144_000,
    plan: "enterprise",
    renewalDays: 33,
    status: "at_risk",
    csm: "Sarah Kim",
    champion: { name: "Lena Park", title: "VP Platform", status: "active" },
    signalCount: 2,
    lastActivity: "3 days ago",
    oneLineWhy: "Competitor mentioned in last Gong call; pricing review scheduled with their CFO",
    isLive: false,
  },
];

export const SOURCES = [
  {
    id: "gmail",
    name: "Gmail",
    category: "Email",
    description: "Inbound + outbound customer email threads",
    status: "connected" as const,
    lastSync: "4m ago",
    todayCount: 213,
    todayLabel: "messages today",
    accent: "#ea4335",
    initial: "M",
  },
  {
    id: "slack",
    name: "Slack",
    category: "Chat",
    description: "Shared customer channels + internal #cs-team",
    status: "connected" as const,
    lastSync: "47s ago",
    todayCount: 84,
    todayLabel: "messages today",
    accent: "#4a154b",
    initial: "S",
  },
  {
    id: "gong",
    name: "Gong",
    category: "Meeting intel",
    description: "Customer call transcripts + sentiment",
    status: "connected" as const,
    lastSync: "12m ago",
    todayCount: 6,
    todayLabel: "transcripts today",
    accent: "#8950ec",
    initial: "G",
  },
  {
    id: "salesforce",
    name: "Salesforce",
    category: "CRM",
    description: "Renewal dates, ARR, contract terms",
    status: "connected" as const,
    lastSync: "2m ago",
    todayCount: 47,
    todayLabel: "records synced",
    accent: "#00a1e0",
    initial: "SF",
  },
  {
    id: "thehog",
    name: "TheHog",
    category: "External signal",
    description: "Stakeholder changes on LinkedIn, X, Reddit (the world your CRM can't see)",
    status: "connected" as const,
    lastSync: "9m ago",
    todayCount: 3,
    todayLabel: "stakeholder events",
    accent: "#f97316",
    initial: "H",
  },
  {
    id: "intercom",
    name: "Intercom",
    category: "Support",
    description: "Customer tickets + severity (coming soon)",
    status: "available" as const,
    lastSync: null,
    todayCount: 0,
    todayLabel: "",
    accent: "#0057ff",
    initial: "I",
  },
  {
    id: "crunchbase",
    name: "Crunchbase + News",
    category: "Market intel",
    description: "Funding events, layoffs, acquisitions at customer companies (coming soon)",
    status: "available" as const,
    lastSync: null,
    todayCount: 0,
    todayLabel: "",
    accent: "#146aff",
    initial: "C",
  },
];
